spring:
  datasource:
    jdbc-url: jdbc:h2:mem:oauth2;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    data: classpath:schemaH2.sql, classpath:dataH2.sql
    hikari:
      jdbc-url:

server:
  port: 8443
